### PR TITLE
feat: support placeholder and selectable-overloads

### LINKED ISSUE #120: R.__ missing
Hey,

The definition for `R.__` (http://ramdajs.com/docs/#__) is missing, is this intentional?

I've tried merging the `Static` interface with a local definition but it doesn't want to play nice :(

```
declare namespace R {
    interface Static {
        __(): any;
    }
}
```
## Update 1
After some more adventures I'm not sure what the type should be either. I modified the `index.d.ts` in my `node_modules/@types/ramda` to include `__` like the following:

```
interface Static {
        __(): any;
        ...
```

But I then couldn't do `R.gt(R.__, 0)` as `R.gt` is `(a: number, b:number) => boolean`. 

This lead to me just defining `R.__` as just `any` (not a function at all) in the interface.

## Update 2
`const R__ = (R as any).__` works.

### LINKED ISSUE #173: Support placeholders and selectable-overloads
## Ideas

If TS cannot select the correct signature, why don't we select it ourselves?

If types are too hard to build manually, why don't we generate it programmatically?

## Types

consider the following types for `R.adjust()`, it looks ugly but works perfectly in my testing.

```ts
type PH = {'@@functional/placeholder': true};
declare const __: PH;

// adjust.d.ts
type adjust = adjust_000;
type adjust_000 = {
  <T, U>(fn: (v: T) => U, index: number, array: T[]): adjust_111<T, U>;
  <T, U>(fn: (v: T) => U, _index: PH, array: T[]): adjust_101<T, U>;
  <T>(_fn: PH, index: number, array: T[]): adjust_011<T>;
  <T>(_fn: PH, _index: PH, array: T[]): adjust_001<T>;
  <T, U>(fn: (v: T) => U, index: number): adjust_110<T, U>;
  (_fn: PH, index: number): adjust_010;
  <X extends "111">(): <T, U>(fn: (v: T) => U, index: number, array: T[]) => adjust_111<T, U>;
  <X extends "101">(): <T, U>(fn: (v: T) => U, _index: PH, array: T[]) => adjust_101<T, U>;
  <X extends "011">(): <T>(_fn: PH, index: number, array: T[]) => adjust_011<T>;
  <X extends "001">(): <T>(_fn: PH, _index: PH, array: T[]) => adjust_001<T>;
  <X extends "11">(): <T, U>(fn: (v: T) => U, index: number) => adjust_110<T, U>;
  <X extends "01">(): (_fn: PH, index: number) => adjust_010;
  <X extends "1">(): <T, U>(fn: (v: T) => U) => adjust_100<T, U>;
  <T, U>(fn: (v: T) => U): adjust_100<T, U>;
};
type adjust_001<T> = {
  <U>(fn: (v: T) => U, index: number): adjust_111<T, U>;
  (_fn: PH, index: number): adjust_011<T>;
  <X extends "11">(): <U>(fn: (v: T) => U, index: number) => adjust_111<T, U>;
  <X extends "01">(): (_fn: PH, index: number) => adjust_011<T>;
  <X extends "1">(): <U>(fn: (v: T) => U) => adjust_101<T, U>;
  <U>(fn: (v: T) => U): adjust_101<T, U>;
};
type adjust_010 = {
  <T, U>(fn: (v: T) => U, array: T[]): adjust_111<T, U>;
  <T>(_fn: PH, array: T[]): adjust_011<T>;
  <X extends "11">(): <T, U>(fn: (v: T) => U, array: T[]) => adjust_111<T, U>;
  <X extends "01">(): <T>(_fn: PH, array: T[]) => adjust_011<T>;
  <X extends "1">(): <T, U>(fn: (v: T) => U) => adjust_110<T, U>;
  <T, U>(fn: (v: T) => U): adjust_110<T, U>;
};
type adjust_011<T> = {
  <U>(fn: (v: T) => U): adjust_111<T, U>;
};
type adjust_100<T, U> = {
  (index: number, array: T[]): adjust_111<T, U>;
  (_index: PH, array: T[]): adjust_101<T, U>;
  <X extends "11">(): (index: number, array: T[]) => adjust_111<T, U>;
  <X extends "01">(): (_index: PH, array: T[]) => adjust_101<T, U>;
  <X extends "1">(): (index: number) => adjust_110<T, U>;
  (index: number): adjust_110<T, U>;
};
type adjust_101<T, U> = {
  (index: number): adjust_111<T, U>;
};
type adjust_110<T, U> = {
  (array: T[]): adjust_111<T, U>;
};
type adjust_111<T, U> = (T | U)[];
```

Since curried function can return itself by calling with non-parameter, we can use generic to select one of those overloads.

If we want to choose one of the overloads in the signature, it just works fine. ( the "11" means choosing the one with 2 ("11".length) parameters and both parameter are not placeholder )

ps. I think something like "11" is easily to notice which case to use, but it can be changed into something else.

```ts
R.adjust<"11">() //=> <T, U>(fn: (v: T) => U, index: number) => adjust_110<T, U>;
```

and with placeholder ( the "01" means choosing the one with 2 ("01".length) parameters, the first parameter is a placeholder, and the last parameter is not a placeholder )

```ts
R.adjust(R.__, 1)<"01">() //=> <T>(_fn: PH, array: T[]) => adjust_011<T>
```

If there are many kinds of the function, like `R.map()` for array, functor, etc., we can create them one by one and mixed them with intersection ( `&` ):

```ts
type map_array = map_array_00;
type map_functor = map_functor_00;
type map = map_array & map_functor;
```

If TS cannot find the correct signature, we can do it ourselves, it just works fine with good looking.

```ts
(R.map as R.map_array)(blah, blah, ...)
```

## Implementation

To implement this types, I wrote a dts DOM library [dts-element](https://github.com/ikatyang/dts-element), the following code will generate the above `adjust.d.ts`.

```ts
import * as dts from 'dts-element';

const name = 'adjust';
const placeholder = new dts.BasicType({name: 'PH'});

const generic_T = new dts.GenericType({name: 'T'});
const generic_U = new dts.GenericType({name: 'U'});

// <T, U>(fn: (v: T) => U, index: number, array: T[]) => (T | U)[]
const function_type = new dts.FunctionType({
  generics: [generic_T, generic_U],
  parameters: [
    new dts.Parameter({
      name: 'fn',
      type: new dts.FunctionType({
        parameters: [
          new dts.Parameter({name: 'v', type: generic_T}),
        ],
        return: generic_U,
      }),
    }),
    new dts.Parameter({name: 'index', type: dts.number_type}),
    new dts.Parameter({name: 'array', type: new dts.ArrayType({owned: generic_T})}),
  ],
  return: new dts.ArrayType({owned: new dts.UnionType({types: [generic_T, generic_U]})}),
});

const types = dts.create_curried_function_types({
  name,
  placeholder,
  type: function_type,
  selectable: true,
});
const document = new dts.Document({children: types});

console.log(document.emit());
```

- [test-cases](https://github.com/ikatyang/dts-element/blob/v1.2.0/src/advanced/__tests__/create-curried-function-types.ts)
- [snapshots](https://github.com/ikatyang/dts-element/blob/v1.2.0/src/advanced/__tests__/__snapshots__/create-curried-function-types.ts.snap)

I am new to functional programming and ramda, I may not consider something else, please correct me if I am wrong.

I think functional programming is a better way to write code and hope to build a full-supported `ramda.d.ts`, let me know if you need any help, I am happy to make this types better and better.

### LINKED ISSUE #181: upgrade to ramda 24.0
[notes](https://github.com/ramda/ramda/issues/2183)

### PR DESCRIPTION
**Pull request by ikatyang**
Fixes #173 
Fixes #181
Fixes #120

Migrate from [ikatyang/types-ramda](https://github.com/ikatyang/types-ramda) v0.24.3, see discussion in #173.

To confirm:

- ~~travis: is `typescript@next` still needed?~~
- [x] travis: need to set a `GH_TOKEN` on travis to deploy `dist-*` branches automatically.
- [x] github: need to add orphan branches to deploy branches.
  - branch names: `dist`, `dist-simple`, `dist-selectable` and `dist-placeholder`
  - `git checkout --orphan $branch-name`
- ~~readme: I have no idea how to modify the roadmap.~~ (seems no need to modify?)
- something I forgot?

Future:

- add scripts to generate DT compatible definition/test files.

### CODE REVIEW

**Comment by tycho01** [comment]
The wait was worth it. :)

> travis: is typescript@next still needed?

Guess we can just manually upgrade, whichever.

> travis: need to set a GH_TOKEN on travis to deploy dist-* branches automatically.

Right, you mentioned that. Can't say I have one but afaik this didn't seem critical.

> readme: I have no idea how to modify the roadmap.

Yeah, whatever. I mean, if I can help it things will move toward more granular type-level operations, but I wouldn't have others worry about that part at least. I suppose the github issue list should suffice to keep things current.

> branches

I had trouble pushing branches as orphan. If it'd do, it did work for non-orphan versions. If `push --force` or whatever could help fix that again, then great.

On that topic, @blakeembrey, could you invite @ikatyang into `types`? I've shifted to working on the higher-level challenges with TS (started a type lib, now making a few compiler PRs) to further get this thing forward, while he's managed to fully rewrite these Ramda typings again.

**Comment by tycho01** [comment]
On `package.json`, just realized a few points from the existing one may have come from expectations of `@types` (linting config) / DT (`typings` prop?).

**Comment by ikatyang** [comment]
- The `typings` prop (value = `index.d.ts`) in `package.json` is not necessary, since it is the default value (`index.d.ts`).

- branches: I'm under the impression that it has to use [`--allow-unrelated-histories`](https://stackoverflow.com/questions/37937984/git-refusing-to-merge-unrelated-histories) to push orphan branches. (normal branch is okay too, but I think orphan branch is clearer)

- I prefer using yarn instead of npm, is `package-lock.json` necessary? if so, I'll replace yarn with npm. (the `package-lock.json` was somehow added in your merge commit)

**Comment by tycho01** [comment]
> I prefer using yarn instead of npm, is `package-lock.json` necessary? if so, I'll replace yarn with npm. (the `package-lock.json` was somehow added in your merge commit)

Sorry, that's fine. I'd felt recent npm simplified things by handling exact version management without the extra dependency, but I don't have a strong preference otherwise; not sure what other considerations might be at play.

> `--allow-unrelated-histories`

Uh, that's part of the `pull` command huh? Sorry if I'm being dense -- how should I use that here?

**Comment by ikatyang** [comment]
Sorry, it does not need `--allow-unrelated-histories` option 😅

```sh
BRANCH=dist
git checkout --orphan $BRANCH
git commit --allow-empty -m "init"
git push --set-upstream origin $BRANCH                                                                                   
```

**Comment by tycho01** [comment]
Done!

**Comment by ikatyang** [comment]
The last thing is about the `GH_TOKEN`, if there's no `GH_TOKEN`, it won't deploy automatically, I can't confirm this since it can only be set on the Travis Settings (Environment Variables, it'll automatically [be encrypted](https://travis-ci.org/ikatyang/types-ramda/builds/264066104#L424)):

- `GH_TOKEN`: [GitHub Personal Access Token](https://github.com/settings/tokens) with `public_repo` permission, it's recommended to use some bot-account like @ikatyang-bot so as to reduce risks.

image

**Comment by tycho01** [comment]
How can I help on this part? So you don't want one from me huh? Does the bot need `@types` write access?

**Comment by ikatyang** [comment]
It's OK from you, but if that `GH_TOKEN` somehow exposed, it'll be dangerous since it'll have all your public repo's write permission. My solution is that I created a bot account and add it as a collaborator, and uses its `GH_TOKEN`, so that it's less dangerous than use our own.

(Just need this repo's write access, but `GH_TOKEN` can only choose the `public_repo` permission)

**Comment by ikatyang** [comment]
Since the `GH_TOKEN` will put in Environment Variables,  it might have some concern of something like [`crossenv` event](http://blog.npmjs.org/post/163723642530/crossenv-malware-on-the-npm-registry), but in short term, I think it's okay to use yours temporarily.

> I guess the Travis account is yours?

I'm not sure what you mean the Travis account?

**Comment by tycho01** [comment]
As in, where can I put this environment variable in? I can't seem to find a page in Github that looks like the one in your screenshot. 😅

**Comment by ikatyang** [comment]
It's on travis 😅, should be in <https://travis-ci.org/types/npm-ramda>

image

**Comment by tycho01** [comment]
Cool, added it in now! :)

**Comment by ikatyang** [comment]
@blakeembrey 

Thanks for inviting me to the @types org. 😀

Can you invite my bot account @ikatyang-bot to be a collaborator of this repo to deploy generated definitions automatically (just like [this](https://github.com/ikatyang/types-ramda/commits/dist))? and set the `master` branch to be a protected branch so that auto-deploy won't accidentally override it, though it's almost the impossible thing to happen, but it'd be great to prevent it. Sorry for bothering you so much.

@tycho01 

I guess we can merge this PR now, and I'll replace the `GH_TOKEN` with my ~~bot's~~ token (looks like I have no permission to add my bot-account as collaborator to this repo, so I'll use mine if there's no other choice) in few days since Travis needs time to sync permission. (I'll tell you when I replaced the token so that you can disable your token)

**Comment by blakeembrey** [comment]
Sure, no problem. What exactly is the bot doing and would it be applicable to the wider organisation? If so, maybe we can find a better approach for you.

**Comment by ikatyang** [comment]
The @ikatyang-bot is just for this repo's deployment: generated four version of the definitions and push them to their own branch: `dist`, `dist-simple`, `dist-placeholder` and `dist-selectable`.

To clarify, this bot account is just for reducing the risk of Personal Access Token, since GitHub can only generate token for `public_repo` and can't generate token only for the specific repo. I'm afraid of something like [`crossenv` event](http://blog.npmjs.org/post/163723642530/crossenv-malware-on-the-npm-registry), so I'd prefer not to use our own account's token directly.

So that people can download which version they want via something like:

```
npm install types/npm-ramda#dist
npm install types/npm-ramda#dist-simple
npm install types/npm-ramda#dist-placeholder
npm install types/npm-ramda#dist-selectable
```

You can see my current deployment in [my repo](https://github.com/ikatyang/types-ramda#usage) for example.

**Comment by ikatyang** [comment]
@tycho01 I've replaced the token on travis with my bot's token.

**Comment by tycho01** [comment]
cool, I've ditched the token; thanks!

**Pull request merged**
