### PR TITLE
fix(pipe-like): add 0-param version

### LINKED ISSUE #283: Add to pipe, pipeP and others case when first function have no arguments
example
```ts
      const getSession = R.pipe(
        () => ({ x: { y: 1 } }),
        R.path(['x', 'y'])
      )
```

expected session to have type `const getSession: () => {} | undefined` but got `const getSession: (v1: {}) => {} | undefined`

though `const session = getSession()` is valid code in js

### PR DESCRIPTION
**Pull request by ikatyang**
Fixes #283

Not sure if this is a good change since it'll need to specify the overload to avoid matching selectable overload (0-param).
```ts
// wrong inference (matched 0-param selectable-overload)
R.pipe(R.map(R.toLower), R.of); //=> () => (string[] | Functor<string> | Record<any, string>)[]
// correct inference
R.pipe(R.map(R.toLower)<'1', 'mixed'>(), R.of); //=> (v1: {}) => (string[] | Functor<string> | Record<never, string>)[]
```

EDIT: with TS v2.6.1, it won't introduce wrong inference.

### CODE REVIEW

**Comment by ikatyang** [comment]
The `matchPhrases` case looks like the only case tested with selectable-overload available.

The other test cases are just simple functions, e.g.

```ts
const double = (x: number): number => x + x;
R.pipe(double, double);
```

It works fine if there's no selectable-overload.

**Comment by tycho01** [comment]
Thanks for clarifying.

In general, I'd be inclined to think the case of arity 1 with overloads would be more common here than arity 0.
Following that line of thought, I wonder if it might be preferable to make the arity 0 case explicitly select an overload rather than the arity 1 one...

**Comment by BjornMelgaard** [comment]
@tycho01 mmm...yep
typical use case - make two actions as one (HTTP-related)

```
const authenticateAndGetSession = R.pipeP(
  api.authenticate,                // () => Promise<object>
  R.path(['AUTH', 'session']) // (object) => string
) as () => Promise<string>
```

**Comment by BjornMelgaard** [comment]
@ikatyang 
I don't think this is very bad that I have to specify type of first function to avoid resulting type of function fallback to `()·=>·{}` (I'm anyway doing this often when using npm-ramda)

example 
```ts
  const m1 = R.map(R.toLower) // complicated type
  const withMapF1 = R.pipe(m, R.of) // ()·=>·{}[]
  const withRes1 = withoutMapF(['asdf']) // string[]

  const m2 = R.map(R.toLower) as (list: string[] | ArrayLike<string>) => string[]
  const withMapF2 = R.pipe(m2, R.of) // (v1:·string[]·|·ArrayLike<string>)·=>·string[][]
  const withRes2 = withoutMapF([ 'asdf' ]) // string[]
```

because `()·=>·{}` works like `any => any` and don't breaks anything (yes?)

P.S.

Can you please add this test to `// @dts-jest:group pipeP`

```
  // @dts-jest:pass:snap -> PromiseLike<number>
  R.pipeP(
    () => Promise.resolve(2),
    (m: number) => Promise.resolve(m / 2),
    R.multiply(5),
  )();
```

**Comment by ikatyang** [comment]
The question is, it'll cause **wrong** type inference if you don't specify the type manually, which will cause a lot of errors for all of our users.

Or maybe we can just enable the 0-param pipe-like for non-`selectable-overload` branch? which won't cause any problem but you'll lose the ability to use selectable-overload.

**Comment by BjornMelgaard** [comment]
@ikatyang can you please explain why this happens? Is it clashing with `selectors`? Can you make minimal example please?

**Comment by ikatyang** [comment]
Repro:

```ts
type Morphism<T, U> = (x: T) => U;
type List<T> = T[] | ArrayLike<T>;
interface Functor<T> {
  map<U>(fn: Morphism<T, U>): Functor<U>;
}

declare function pipe<R1>(fn1: () => R1): () => R1;
declare function pipe<V1, R1>(fn1: (v1: V1) => R1): (v1: V1) => R1;
declare function pipe<V1, V2, R1>(fn1: (v1: V1, v2: V2) => R1): (v1: V1, v2: V2) => R1;
declare function pipe<R1, R2>(fn1: () => R1, fn2: (v: R1) => R2): () => R2;
declare function pipe<V1, R1, R2>(fn1: (v1: V1) => R1, fn2: (v: R1) => R2): (v1: V1) => R2;
declare function pipe<V1, V2, R1, R2>(fn1: (v1: V1, v2: V2) => R1, fn2: (v: R1) => R2): (v1: V1, v2: V2) => R2;
declare function pipe<R1, R2, R3>(fn1: () => R1, fn2: (v: R1) => R2, fn3: (v: R2) => R3): () => R3;
declare function pipe<V1, R1, R2, R3>(fn1: (v1: V1) => R1, fn2: (v: R1) => R2, fn3: (v: R2) => R3): (v1: V1) => R3;
declare function pipe<V1, V2, R1, R2, R3>(fn1: (v1: V1, v2: V2) => R1, fn2: (v: R1) => R2, fn3: (v: R2) => R3): (v1: V1, v2: V2) => R3;

declare const map: map_00;
type map_00 = {
    <T, U>(fn: Morphism<T, U>): map_10<T, U>;
};
type map_10<T, U> = {
    (list: List<T>): map_list_11<U>;
    (functor: Functor<T>): map_functor_11<U>;
    // <$SEL extends "1", $KIND extends "list">(): (list: List<T>) => map_list_11<U>;
    // <$SEL extends "1", $KIND extends "functor">(): (functor: Functor<T>) => map_functor_11<U>;
    // <$SEL extends "1", $KIND extends "object">(): <K extends string>(object: Record<K, T>) => map_object_11<U, K>;
    <K extends string>(object: Record<K, T>): map_object_11<U, K>;
};
type map_list_11<U> = U[];
type map_functor_11<U> = Functor<U>;
type map_object_11<U, K extends string> = Record<K, U>;

const result = pipe(map((x: string) => x));
//=> if comment out selectable-overloads: (correct inference)
//  (v1: Record<any, string>) => Record<any, string>
//=> otherwise: (wrong inference)
//  () => Record<any, string>
```

Interestingly, if there's no generic on the last signature, everything works fine:

```diff
-<K extends string>(object: Record<K, T>): map_object_11<U, K>;
+(object: Record<string, T>): map_object_11<U, string>;
```

I'm not sure if this is a TS bug.

**Comment by BjornMelgaard** [comment]
@ikatyang why I getting right result in playground? [link](https://www.typescriptlang.org/play/index.html#src=type%20Morphism%3CT%2C%20U%3E%20%3D%20(x%3A%20T)%20%3D%3E%20U%3B%0D%0Atype%20List%3CT%3E%20%3D%20T%5B%5D%20%7C%20ArrayLike%3CT%3E%3B%0D%0Ainterface%20Functor%3CT%3E%20%7B%0D%0A%20%20map%3CU%3E(fn%3A%20Morphism%3CT%2C%20U%3E)%3A%20Functor%3CU%3E%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20function%20pipe%3CR1%3E(fn1%3A%20()%20%3D%3E%20R1)%3A%20()%20%3D%3E%20R1%3B%0D%0Adeclare%20function%20pipe%3CV1%2C%20R1%3E(fn1%3A%20(v1%3A%20V1)%20%3D%3E%20R1)%3A%20(v1%3A%20V1)%20%3D%3E%20R1%3B%0D%0Adeclare%20function%20pipe%3CV1%2C%20V2%2C%20R1%3E(fn1%3A%20(v1%3A%20V1%2C%20v2%3A%20V2)%20%3D%3E%20R1)%3A%20(v1%3A%20V1%2C%20v2%3A%20V2)%20%3D%3E%20R1%3B%0D%0Adeclare%20function%20pipe%3CR1%2C%20R2%3E(fn1%3A%20()%20%3D%3E%20R1%2C%20fn2%3A%20(v%3A%20R1)%20%3D%3E%20R2)%3A%20()%20%3D%3E%20R2%3B%0D%0Adeclare%20function%20pipe%3CV1%2C%20R1%2C%20R2%3E(fn1%3A%20(v1%3A%20V1)%20%3D%3E%20R1%2C%20fn2%3A%20(v%3A%20R1)%20%3D%3E%20R2)%3A%20(v1%3A%20V1)%20%3D%3E%20R2%3B%0D%0Adeclare%20function%20pipe%3CV1%2C%20V2%2C%20R1%2C%20R2%3E(fn1%3A%20(v1%3A%20V1%2C%20v2%3A%20V2)%20%3D%3E%20R1%2C%20fn2%3A%20(v%3A%20R1)%20%3D%3E%20R2)%3A%20(v1%3A%20V1%2C%20v2%3A%20V2)%20%3D%3E%20R2%3B%0D%0Adeclare%20function%20pipe%3CR1%2C%20R2%2C%20R3%3E(fn1%3A%20()%20%3D%3E%20R1%2C%20fn2%3A%20(v%3A%20R1)%20%3D%3E%20R2%2C%20fn3%3A%20(v%3A%20R2)%20%3D%3E%20R3)%3A%20()%20%3D%3E%20R3%3B%0D%0Adeclare%20function%20pipe%3CV1%2C%20R1%2C%20R2%2C%20R3%3E(fn1%3A%20(v1%3A%20V1)%20%3D%3E%20R1%2C%20fn2%3A%20(v%3A%20R1)%20%3D%3E%20R2%2C%20fn3%3A%20(v%3A%20R2)%20%3D%3E%20R3)%3A%20(v1%3A%20V1)%20%3D%3E%20R3%3B%0D%0Adeclare%20function%20pipe%3CV1%2C%20V2%2C%20R1%2C%20R2%2C%20R3%3E(fn1%3A%20(v1%3A%20V1%2C%20v2%3A%20V2)%20%3D%3E%20R1%2C%20fn2%3A%20(v%3A%20R1)%20%3D%3E%20R2%2C%20fn3%3A%20(v%3A%20R2)%20%3D%3E%20R3)%3A%20(v1%3A%20V1%2C%20v2%3A%20V2)%20%3D%3E%20R3%3B%0D%0A%0D%0Adeclare%20const%20map%3A%20map_00%3B%0D%0Atype%20map_00%20%3D%20%7B%0D%0A%20%20%20%20%3CT%2C%20U%3E(fn%3A%20Morphism%3CT%2C%20U%3E)%3A%20map_10%3CT%2C%20U%3E%3B%0D%0A%7D%3B%0D%0Atype%20map_10%3CT%2C%20U%3E%20%3D%20%7B%0D%0A%20%20%20%20(list%3A%20List%3CT%3E)%3A%20map_list_11%3CU%3E%3B%0D%0A%20%20%20%20(functor%3A%20Functor%3CT%3E)%3A%20map_functor_11%3CU%3E%3B%0D%0A%20%20%20%20%3C%24SEL%20extends%20%221%22%2C%20%24KIND%20extends%20%22list%22%3E()%3A%20(list%3A%20List%3CT%3E)%20%3D%3E%20map_list_11%3CU%3E%3B%0D%0A%20%20%20%20%3C%24SEL%20extends%20%221%22%2C%20%24KIND%20extends%20%22functor%22%3E()%3A%20(functor%3A%20Functor%3CT%3E)%20%3D%3E%20map_functor_11%3CU%3E%3B%0D%0A%20%20%20%20%3C%24SEL%20extends%20%221%22%2C%20%24KIND%20extends%20%22object%22%3E()%3A%20%3CK%20extends%20string%3E(object%3A%20Record%3CK%2C%20T%3E)%20%3D%3E%20map_object_11%3CU%2C%20K%3E%3B%0D%0A%20%20%20%20%3CK%20extends%20string%3E(object%3A%20Record%3CK%2C%20T%3E)%3A%20map_object_11%3CU%2C%20K%3E%3B%0D%0A%7D%3B%0D%0Atype%20map_list_11%3CU%3E%20%3D%20U%5B%5D%3B%0D%0Atype%20map_functor_11%3CU%3E%20%3D%20Functor%3CU%3E%3B%0D%0Atype%20map_object_11%3CU%2C%20K%20extends%20string%3E%20%3D%20Record%3CK%2C%20U%3E%3B%0D%0A%0D%0Aconst%20result%20%3D%20pipe(map((x%3A%20string)%20%3D%3E%20x))%3B%0D%0A%2F%2F%3D%3E%20if%20comment%20out%20selectable-overloads%3A%20(correct%20inference)%0D%0A%2F%2F%20%20(v1%3A%20Record%3Cany%2C%20string%3E)%20%3D%3E%20Record%3Cany%2C%20string%3E%0D%0A%2F%2F%3D%3E%20otherwise%3A%20(wrong%20inference)%0D%0A%2F%2F%20%20()%20%3D%3E%20Record%3Cany%2C%20string%3E%0D%0A)

________

> Or maybe we can just enable the 0-param pipe-like for non-selectable-overload branch? which won't cause any problem but you'll lose the ability to use selectable-overload.

Yes, can you do it please :smiley:

**Comment by ikatyang** [comment]
It appears the bug I mentioned above was fixed in TS v2.6.1, so no need to enable in specific branch. But you may have to build the types yourself as a temporary workaround:

```sh
# clone this branch
yarn
yarn run build
# the built types should be in ./ramda/dist
```

since there're some problems for upgrading v2.6.1 (#310, but the `pipe` part looks fine) and I'm busy recently, will fix it next weekend.

**Comment by BjornMelgaard** [comment]
@ikatyang awesome news, looking forward)

**Pull request merged**
